baseURL: 'https://ejammy.github.io/'
languageCode: en-us
title: EJam's Space
theme: hugo-PaperMod

params:
  profileMode:
    enabled: true
    subtitle: "I type stuff and hope cool things come out"
    buttons:
      - name: Posts
        url: "/posts"
  mainSections:
  - posts
  - docs
  comments: true

menu:
  main:
    - identifier: playground
      name: "Playground"
      url: "/playground"
      weight: 100
    - identifier: posts
      name: "Posts"
      url: "/posts"
      weight: 1
    - identifier: past-work
      name: Past Work
      url: /past-work
      weight: 2
    # - identifier: categories
    #   name: Categories
    #   url: /categories/
    #   weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: about
      name: About
      url: /about
      weight: 0

# render html
markup:
  goldmark:
    renderer:
      unsafe: true

googleAnalytics: G-TBJXCCN715
disqusShortname: ejammy
